### ISSUE TITLE
DatabaseHelper.java line 55 com.onaio.steps.helper.DatabaseHelper.onUpgrade

### ISSUE THREAD

**Issue by ukanga** [onaio/steps-app#167]
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.onaio.steps/com.onaio.steps.activities.HouseholdListActivity}: android.database.sqlite.SQLiteException: duplicate column name: Server_Status (code 1 SQLITE_ERROR[1]): , while compiling: ALTER TABLE household ADD COLUMN Server_Status TEXT default 'NOT_SENT'

```java
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.onaio.steps/com.onaio.steps.activities.HouseholdListActivity}: android.database.sqlite.SQLiteException: duplicate column name: Server_Status (code 1 SQLITE_ERROR[1]): , while compiling: ALTER TABLE household ADD COLUMN Server_Status TEXT default 'NOT_SENT'
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by ukanga** [comment]
Caused by android.database.sqlite.SQLiteException
duplicate column name: Server_Status (code 1 SQLITE_ERROR[1]): , while compiling: ALTER TABLE household ADD COLUMN Server_Status TEXT default 'NOT_SENT'
```java
Caused by android.database.sqlite.SQLiteException: duplicate column name: Server_Status (code 1 SQLITE_ERROR[1]): , while compiling: ALTER TABLE household ADD COLUMN Server_Status TEXT default 'NOT_SENT'
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1463)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:901)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2437)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2359)
       at com.onaio.steps.helper.DatabaseHelper.onUpgrade(DatabaseHelper.java:55)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:489)
       at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:411)
       at com.onaio.steps.helper.DatabaseHelper.exec(DatabaseHelper.java:101)
       at com.onaio.steps.model.Household.getAllInOrder(Household.java:247)
       at com.onaio.steps.activities.HouseholdListActivity.getViewPreparer(HouseholdListActivity.java:95)
       at com.onaio.steps.activities.HouseholdListActivity.setLayout(HouseholdListActivity.java:53)
       at com.onaio.steps.activities.HouseholdListActivity.prepareScreen(HouseholdListActivity.java:42)
       at com.onaio.steps.activities.BaseListActivity.onCreate(BaseListActivity.java:48)
       at android.app.Activity.performCreate(Activity.java:8207)
       at android.app.Activity.performCreate(Activity.java:8191)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)```
