### ISSUE TITLE
Minification of code

### ISSUE THREAD

**Issue by bkimondiu** [onaio/steps-app#203]
Confirm if we need to update our configuration to upload the mapping file [https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=android](https://www.google.com/url?q=https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform%3Dandroid&sa=D&source=docs&ust=1652099433119830&usg=AOvVaw3Cqutz2asWoAU6Cjli0qe8)

**Comment by owais-vd** [comment]
i've checked the release build with a test crash on crashlytics dashboard the trace is not obfuscated and readable by human. @ekigamba @bkimondiu

**Comment by owais-vd** [comment]
```java
Fatal Exception: java.lang.RuntimeException: false Release crash test on crashlytics
       at com.onaio.steps.StepsApplication.lambda$onCreate$0(StepsApplication.java:4)
       at com.onaio.steps.-$$Lambda$StepsApplication$GcxWTwwqghPGL43U9oLoPUxiROc.run(-.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
